# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uclapi.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=75)),
                ('private_roombookings', models.BooleanField(default=False)),
                ('private_timetable', models.BooleanField(default=False)),
                ('private_uclu', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default=uclapi.helpers.generate_state, max_length=70, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='uclapi.OAuthToken')),
            ],
        ),
    ]
