# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uclapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='token',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uclapi.OAuthToken'),
        ),
    ]
