# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uclapi', '0002_auto_20170602_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthtoken',
            name='code',
            field=models.CharField(max_length=80),
        ),
    ]
